{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPaa99mteLVlW6rJ50ixh/t",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/jeanpaul-lab/gdp-dashboard/blob/main/app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# ========================================\n",
        "# MASS HAUL WEB APP — FULL PROFESSIONAL VERSION\n",
        "# Upload CSV → Get Report + Graph + All Calculations\n",
        "# ========================================\n",
        "\n",
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "import numpy as np\n",
        "\n",
        "st.set_page_config(page_title=\"Mass Haul Pro\", layout=\"wide\")\n",
        "st.title(\"Mass Haul Diagram Pro\")\n",
        "st.write(\"**By Jean Paul | UR-CST Transportation Engineering** — Optimize earthwork & save millions.\")\n",
        "\n",
        "# === UPLOAD CSV ===\n",
        "uploaded_file = st.file_uploader(\"Upload CSV: Chainage (m), Cut Volume (m³), Fill Volume (m³), Shrinkage Factor\", type=\"csv\")\n",
        "\n",
        "if uploaded_file is not None:\n",
        "    df = pd.read_csv(uploaded_file)\n",
        "    if df.shape[1] != 4:\n",
        "        st.error(\"CSV must have 4 columns: Chainage (m), Cut Volume (m³), Fill Volume (m³), Shrinkage Factor\")\n",
        "    else:\n",
        "        st.success(\"Data loaded!\")\n",
        "        st.dataframe(df.style.format(\"{:.1f}\"))\n",
        "\n",
        "        # === CALCULATIONS ===\n",
        "        df['Adjusted Cut'] = df['Cut Volume (m³)'] / df['Shrinkage Factor']\n",
        "        df['Net Volume'] = df['Adjusted Cut'] - df['Fill Volume (m³)']\n",
        "        df['Cumulative'] = df['Net Volume'].cumsum()\n",
        "\n",
        "        # Max Cut/Fill\n",
        "        max_cut = df['Cut Volume (m³)'].max()\n",
        "        max_fill = df['Fill Volume (m³)'].max()\n",
        "        max_cut_station = df[df['Cut Volume (m³)'] == max_cut]['Chainage (m)'].iloc[0]\n",
        "        max_fill_station = df[df['Fill Volume (m³)'] == max_fill]['Chainage (m)'].iloc[0]\n",
        "\n",
        "        # Balance Points\n",
        "        balance_points = []\n",
        "        for i in range(len(df)-1):\n",
        "            y1, y2 = df['Cumulative'].iloc[i], df['Cumulative'].iloc[i+1]\n",
        "            if y1 * y2 <= 0 and y1 != y2:\n",
        "                x1, x2 = df['Chainage (m)'].iloc[i], df['Chainage (m)'].iloc[i+1]\n",
        "                zero_at = x1 + (x2 - x1) * abs(y1) / (abs(y1) + abs(y2))\n",
        "                balance_points.append(round(zero_at))\n",
        "\n",
        "        # Free Haul (100m)\n",
        "        free_haul_distance = 100\n",
        "        free_haul_volume = 0\n",
        "        for i in range(len(df)-1):\n",
        "            dist = df['Chainage (m)'].iloc[i+1] - df['Chainage (m)'].iloc[i]\n",
        "            vol = abs(df['Net Volume'].iloc[i])\n",
        "            if dist <= free_haul_distance:\n",
        "                free_haul_volume += vol\n",
        "\n",
        "        # Average Haul\n",
        "        total_haul_volume = 0\n",
        "        total_haul_distance = 0\n",
        "        for i in range(len(df)-1):\n",
        "            dist = df['Chainage (m)'].iloc[i+1] - df['Chainage (m)'].iloc[i]\n",
        "            vol = abs(df['Net Volume'].iloc[i])\n",
        "            if dist > free_haul_distance:\n",
        "                total_haul_volume += vol\n",
        "                total_haul_distance += vol * (dist - free_haul_distance)\n",
        "\n",
        "        avg_haul_distance = total_haul_distance / total_haul_volume if total_haul_volume > 0 else 0\n",
        "        avg_haul_volume = total_haul_volume\n",
        "\n",
        "        # Summary\n",
        "        total_raw_cut = df['Cut Volume (m³)'].sum()\n",
        "        total_adj_cut = df['Adjusted Cut'].sum()\n",
        "        total_fill = df['Fill Volume (m³)'].sum()\n",
        "        borrow = max(0, total_fill - total_adj_cut)\n",
        "        surplus = max(0, total_adj_cut - total_fill)\n",
        "        savings = borrow * 8000\n",
        "        revenue = surplus * 8000\n",
        "\n",
        "        # === DISPLAY REPORT ===\n",
        "        st.subheader(\"Earthwork Summary\")\n",
        "        col1, col2, col3 = st.columns(3)\n",
        "        col1.metric(\"Total Cut (Raw)\", f\"{total_raw_cut:,.0f} m³\")\n",
        "        col1.metric(\"Adjusted Cut\", f\"{total_adj_cut:,.1f} m³\")\n",
        "        col2.metric(\"Total Fill\", f\"{total_fill:,.0f} m³\")\n",
        "        col2.metric(\"Borrow Needed\", f\"{borrow:,.1f} m³\")\n",
        "        col3.metric(\"Surplus Cut\", f\"{surplus:,.1f} m³\")\n",
        "        col3.metric(\"Net Revenue\", f\"RWF {revenue - borrow*8000:,.0f}\")\n",
        "\n",
        "        st.metric(\"Max Savings\", f\"RWF {savings:,.0f}\", \"Reuse & Sell Surplus\")\n",
        "\n",
        "        st.subheader(\"Advanced Metrics\")\n",
        "        col4, col5 = st.columns(2)\n",
        "        col4.metric(\"Max Cut\", f\"{max_cut:,.0f} m³ at {max_cut_station} m\")\n",
        "        col4.metric(\"Max Fill\", f\"{max_fill:,.0f} m³ at {max_fill_station} m\")\n",
        "        col4.metric(\"Free Haul Volume\", f\"{free_haul_volume:,.0f} m³\")\n",
        "        col5.metric(\"Avg Haul Distance\", f\"{avg_haul_distance:,.1f} m\")\n",
        "        col5.metric(\"Avg Haul Volume\", f\"{avg_haul_volume:,.0f} m³\")\n",
        "        st.write(f\"Balance Points: {', '.join(map(str, balance_points))} m\")\n",
        "\n",
        "        # === GRAPH ===\n",
        "        st.subheader(\"Mass Haul Diagram\")\n",
        "        fig, ax = plt.subplots(figsize=(12, 6))\n",
        "        ax.plot(df['Chainage (m)'], df['Cumulative'], 'bo-', linewidth=2, label='Mass Haul Curve')\n",
        "        ax.axhline(0, color='red', linestyle='--', label='Balance Line')\n",
        "        for bp in balance_points:\n",
        "            ax.axvline(bp, color='green', linestyle=':', label=f'Balance @ {bp}m' if balance_points.index(bp)==0 else None)\n",
        "        ax.annotate(f\"Max Cut: {max_cut:,}\", (max_cut_station, ax.get_ylim()[1]*0.8), color='blue')\n",
        "        ax.annotate(f\"Max Fill: {max_fill:,}\", (max_fill_station, ax.get_ylim()[0]*1.2), color='red')\n",
        "        ax.fill_between(df['Chainage (m)'], df['Cumulative'], where=(df['Cumulative'] >= 0), color='lightgreen', alpha=0.5)\n",
        "        ax.fill_between(df['Chainage (m)'], df['Cumulative'], where=(df['Cumulative'] < 0), color='lightcoral', alpha=0.5)\n",
        "        ax.set_title('Mass Haul Diagram')\n",
        "        ax.set_xlabel('Chainage (m)')\n",
        "        ax.set_ylabel('Cumulative Volume (m³)')\n",
        "        ax.legend()\n",
        "        ax.grid(alpha=0.3)\n",
        "        st.pyplot(fig)\n",
        "\n",
        "        # === DOWNLOAD ===\n",
        "        st.download_button(\"Download Report PNG\", fig.savefig(\"report.png\", dpi=300, bbox_inches='tight'), file_name=\"mhd_report.png\")\n",
        "\n",
        "        # === PAYMENT ===\n",
        "        st.subheader(\"Get Full PDF + Consultation\")\n",
        "        st.write(\"Fee: RWF 500,000 via M-Pesa\")\n",
        "        name = st.text_input(\"Your Name\")\n",
        "        phone = st.text_input(\"Phone (+250...)\")\n",
        "        if st.button(\"Request Payment\"):\n",
        "            st.success(f\"Payment link sent to {phone}!\")\n",
        "\n",
        "st.caption(\"Contact: Jean Paul | +250 78X XXX XXX\")"
      ],
      "metadata": {
        "id": "Msr1YiLTn0gE"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}